services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - VITE_API_URL=http://auth-service:3002/api
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
    depends_on:
      auth-service:
        condition: service_started
      notifications-service:
        condition: service_started
      posts-service:
        condition: service_started
    restart: unless-stopped
    networks:
      - forum-network


  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    ports:
      - '3002:3002'
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./apps/auth-service/.env
    restart: unless-stopped
    networks:
      - forum-network

  notifications-service:
    build:
      context: .
      dockerfile: ./apps/notifications-service/Dockerfile
    ports:
      - '3003:3003'
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - forum-network

  posts-service:
    build:
      context: .
      dockerfile: ./apps/posts-service/Dockerfile
    ports:
      - '3004:3004'
    env_file:
      - ./apps/posts-service/.env  
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - forum-network

  db:
    image: postgres:17.5-alpine3.21
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jungle-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jungle-db"]
      interval: 3s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    networks:
      - forum-network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped
    networks:
      - forum-network

networks:
  forum-network:
    driver: bridge

volumes:
  postgres_data:
  rabbit_data:
